---
settings:
  name: Upgrade Health Checker
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: 升级 Health Checker 文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: 新增功能
      url: "/whats-new.html"
  - title: 开始使用
    entries:
    - title: 了解 Upgrade Health Checker
      url: "/learn-about-upgrade-health-checker.html"
    - title: 设置 Upgrade Health Checker
      url: "/set-up-upgrade-health-checker.html"
  - title: 使用 Upgrade Health Checker
    entries:
    - title: 生成 ONTAP 升级报告
      url: "/generate-report-upgrade-health-checker.html"
    - title: 自动生成报告
      url: "/automate-report-upgrade-health-checker.html"
  - title: 升级运行状况检查器的输入参数
    url: "/upgrade-health-checker-input-parameters.html"
  - title: 常见问题解答
    url: "/faq-upgrade-health-checker.html"
  - title: 法律声明
    url: "/legal-notices.html"
